config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  
  
  resources :shoes do
    member do
      post 'like'
    end
  end
  
  resources :runners, except: [:new]
  resources :runs 
  
  get '/register', to: 'runners#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :runner
  belongs_to :shoe
  
  validates_uniqueness_of :runner, scope: :shoe
end

app/models/run.rb
class Run < ActiveRecord::Base
  belongs_to :shoe
  belongs_to :runner
  
  validates :runner_id, presence: true
  validates :shoe_id, presence: true
  validates :run_date, presence: true
  validates :run_distance, presence: true
end

app/models/runner.rb
class Runner < ActiveRecord::Base
  has_many :shoes
  has_many :likes
  has_many :runs, through: :shoes
  before_save { self.email = email.downcase }
  validates :runnername, presence: true, length: {minimum: 3, maximum: 40 }
  VALID_EMAIL_REGEX = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
  validates :email, presence: true, length: {maximum: 105 },
                                    uniqueness: { case_sensitive: false },
                                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  belongs_to :runner
  has_many :likes
  has_many :runs
  validates :runner_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }
  mount_uploader :picture, PictureUploader
  validate :picture_size
  default_scope -> { order(updated_at: :desc) }
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like:false).size
  end
  
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  
  def current_user
    @current_user ||= Runner.find(session[:runner_id]) if session[:runner_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action."
      redirect_to :back
    end
  end
  
  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def new
    
  end
  
  def create
    runner = Runner.find_by(email: params[:email])
    if runner && runner.authenticate(params[:password])
      session[:runner_id] = runner.id
      flash[:success] = "Awesome! You're logged in!"
      redirect_to shoes_path
    else
      flash.now[:danger] = "Yikes! Your email or password isn't correct."
      render 'new'
    end
    
  end
    
  def destroy
    session[:runner_id] = nil
    flash[:success] = "You've been logged out. Sorry to see you go!"
    redirect_to root_path
  end
  
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to shoes_path if logged_in?
  end

end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_action :set_runner, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  

  def index
    @runners = Runner.paginate(page: params[:page], per_page: 3)
  end
  
  def new
    @runner = Runner.new
  end

  def create
    @runner = Runner.new(runner_params)
      if @runner.save
        flash[:success] = "You're now a Runner! Hooray!"
        session[:runner_id] = @runner.id
        redirect_to shoes_path
      else
        render 'new'
      end
  end
  
  def edit
  end
  
  def update
      if @runner.update(runner_params)
        flash[:success] = "Your profile has been successfully updated!"
        redirect_to runner_path(@runner)
      else
        render 'edit'
      end
  end
  
  def show
    @shoes = @runner.shoes.paginate(page: params[:page], per_page: 3)
  end
  
  private
  
  def runner_params
    params.require(:runner).permit(:runnername, :email, :password)
  end
  
  def set_runner
    @runner = Runner.find(params[:id])
  end
  
  def require_same_user
    if current_user != @runner
      flash[:danger] = "You can only edit your own profile"
      redirect_to root_path
    end
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: [:edit, :update, :show, :like]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]
  
  def new
    @run = Run.new
  end

  def show
  end
  
  def index
    @runs = Run.paginate(page: params[:page], per_page: 4)
  end

  def create
    @run = Run.new(shoe_params)
    @run.runner = current_user
    
    if @run.save
      flash[:success] = "You successfully logged your run! Yay!"
      redirect_to shoes_path
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @run.update(run_params)
      flash[:success] = "You updated your run successfully! Yay!"
      redirect_to run_path(@run)
    else
      render :edit
    end
  end


  
  
private
  
  def run_params
    params.require(:run).permit(:run_distance, :shoe_id)
  end
    
  def set_run
    @shoe = Run.find(params[:id])
  end
    
  def require_same_user
    if current_user != @run.runner
      flash[:danger] = "You can only edit your own runs!"
      redirect_to shoes_path
    end
  end

  
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:edit, :update, :show, :like]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]
  

  def index
    @shoes = Shoe.paginate(page: params[:page], per_page: 4)
  end


  def show
  end

  def new
    @shoe = Shoe.new
  end
  
  def create
    @shoe = Shoe.new(shoe_params)
    @shoe.runner = current_user
    
    if @shoe.save
      flash[:success] = "Your shoe was created successfully! Yay!"
      redirect_to shoes_path
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @shoe.update(shoe_params)
      flash[:success] = "Your shoe was updated successfully! Yay!"
      redirect_to shoe_path(@shoe)
    else
      render :edit
    end
  end

  def like
    like = Like.create(like: params[:like], runner: current_user, shoe: @shoe)
    if like.valid?
      flash[:success] = "You like this shoe! You've got good taste!"
      redirect_to :back
    else
      flash[:danger] = "No way, Jose! You can only vote on a shoe once!"
      redirect_to :back
    end
  end
  


  private
  
    def shoe_params
      params.require(:shoe).permit(:name, :summary, :description, :picture)
    end
    
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end
    
    def require_same_user
      if current_user != @shoe.runner
        flash[:danger] = "You can only edit your own shoes!"
        redirect_to shoes_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(runner, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(runner.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: runner.runnername, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<div class="footer">
      <p>&copy; Geek Fitness - Milemarker 2016</p> 

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
      <%= link_to "Milemarker", root_path, class: "btn btn-large btn-success", id: "logo" %>
          <div class="nav_item">
            <%= link_to "All Shoes", shoes_path, class: "btn btn-default btn-warning" %>
          </div>
          <div class="nav_item">
            <%= link_to "Log Your Run!", new_run_path, class: "btn btn-default btn-warning" %>
          </div>



          <% if logged_in? %>
            <div class="nav_item">
              <%= link_to "Create A New Running Shoe!", new_shoe_path, class: "btn btn-default btn-warning" %>
            </div>
            <ul class="nav_item">
              <li class="dropdown">
                <%= link_to "#", class: "btn btn-default btn-danger droptown-toggle", "data-toggle" => "dropdown" do %>
                  <%= current_user.runnername %> <b class="caret"></b>
                <% end %>
                <ul class="dropdown-menu">
                  <li><%= link_to "View Profile", runner_path(current_user) %></li>
                  <li><%= link_to "Edit Profile", edit_runner_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Logout", logout_path %></li>
                </ul>
              </li>
            </ul>
          <% else %>
            <div class="nav_item">
              <%= link_to "Login", login_path, class: "btn btn-default btn-success" %>
            </div>
          <% end %>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Milemarker - Track Your Running Shoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/navigation' %>

    <div class="container">
      
      <%= render 'layouts/messages' %>
      
      <%= yield %>
      
<%= render 'layouts/footer' %>
      
    </div>
    
    </div>
</body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/page_title', title: "Login" %>

<div class="row">
  <div class="well col-md-6 col-md-offset-3">
    <%= form_tag '/login' do %>

    <%= label_tag :email %>
    <%= text_field_tag :email %>
    
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    
    <%=submit_tag 'Login', class: 'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
<div class="center jumbotron">
  <h1>Welcome to Milemarker!</h1>
  <h2>You can use Milemarker to track the life of your running shoes, upload photos of your progress, and compare your mileage to other runners to ensure you're getting every last step you paid for!</h2>
  <%= link_to "Sign Up Now!", register_path, class: "btn btn-lg btn-success" %>
</div>

<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">View shoes as guest user</h3>
    <h2 class="left">Browse and view shoes as a guest</h2>
    <p><%= link_to "Browse Shoe Listings", shoes_path, class: "btn btn-warning btn-small" %> </p>
    
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">View All Runners</h3>
    <h2 class="left">Want to see all the registered runners?</h2>
    <p><%= link_to "View All Runners", runners_path, class: "btn btn-warning btn-small" %> </p>
    
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">Login</h3>
    <h2 class="left">Add/update your shoes, like/dislike shoes, and much more!  </h2>
    <p><%= link_to "Log in to your account", login_path, class: "btn btn-warning btn-small" %> </p>
    
  </div>
  
</div>

</div>

app/views/runners/_form.html.erb
<%= render 'shared/errors', obj: @runner %>

<div class="row">
  <div class="well col-md-8 col-offset-2">
    <%= form_for @runner do |f| %>
      <%= f.label "Username" %>
      <%= f.text_field :runnername %>
      
      <%= f.label :email %>
      <%= f.email_field :email %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>
     
      <%= f.submit(@runner.new_record? ? 'Register New Runner' : 'Edit Profile', class: "btn btn-success") %>
      
    <% end %>
    
  </div>
  
</div>

app/views/runners/edit.html.erb
<%= render 'shared/page_title', title: "Edit Your Profile!" %>

<%= render 'form' %>

app/views/runners/index.html.erb
<%= render 'shared/page_title', title: 'All Runners' %>

<ul class="nav nav-tabs">
  <li class=>
    <%= link_to "Shoes", shoes_path %>
  </li>
  <li class="active">
    <%= link_to "Runners", runners_path %>
  </li>
</ul>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= will_paginate %>
  </div>
</div>

<% @runners.each do |runner| %>
  <div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= link_to gravatar_for(runner, size: 200), runner_path(runner) %>
    <p><h5>Runner name: <%= runner.runnername %></h5></p>
  </div>
</div>

<% end %>

app/views/runners/new.html.erb
<%= render 'shared/page_title', title: "Register and Become a Runner Today!" %>

<%= render 'form' %>

app/views/runners/show.html.erb
<%= render 'shared/page_title', title: "Runner: " +@runner.runnername %>

<div class="row"></div>
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @runner, size: 200 %>
    <hr/>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <h3><em>Shoes:</em></h3>
    <%= will_paginate @shoes %>
  </div>
</div>

<% @shoes.each do |shoe| %>
  <div class="row">
    <div class="col-lg-6 well col-lg-offset-3">
      <h4><%= link_to shoe.name, shoe_path(shoe) %></h4>
        <p><%= shoe.summary %></p>
        
          <p><span class='quiet'>Created <small><%= time_ago_in_words(shoe.created_at) %> ago;          </small></span>
            <span class='quiet'>Updated <small><%= time_ago_in_words(shoe.updated_at) %> ago
            </small></span></p>
        
        <div class="pull-right">
          <%= link_to like_shoe_path(shoe, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= shoe.thumbs_up_total %>
            <% end %> &nbsp&nbsp&nbsp&nbsp
            <%= link_to like_shoe_path(shoe, like: false), method: :post do %>
              <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= shoe.thumbs_down_total %>
          <% end %>
        </div>
    </div>
  </div>

<% end %>

app/views/runs/_form.html.erb
<%= render 'shared/errors', obj: @run %>

<div class="row">
  <div class="well col-md-8 col-offset-2">
    <%= form_for @run do |f| %>
      <%= f.label "How long was your run?" %>
      <%= f.text_field :run_distance %> <!-- How do I create this method? -->

      <div class="form-group">
        <%= f.label "Which shoes were you wearing?" %> 
        <%= f.select(:shoes, options_for_select([[@shoe.name, 1], [@shoe.name, 2]]), {}, {class: "form-control"}) %>
      </div>
     
      <%= f.submit(@run.new_record? 'Add run to selected shoe', class: "btn btn-success") %>
      
    <% end %>
    
  </div>
  
</div>

app/views/runs/index.html.erb
Eventually, this will have the list of all your runs in it.

Showing a table of Runs with their linked shoes as thumbnails beside it.

app/views/runs/new.html.erb
<h1>Add a Run to an Existing Running Shoe!</h1>

<p>Here, you will add individual runs to shoes so you can track total mileage.</p>

<%= render 'form' %>
Eventually, there will be a form here to add runs to your individual pairs of shoes.

app/views/runs/show.html.erb
<%= render 'shared/page_title', title: @run.name %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors:</h5>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
  <h1><%= title %></h1>
  <hr/>
</p>

app/views/shoes/_form.html.erb
<%= render 'shared/errors', obj: @shoe %>

<div class="row">
  <div class="well col-md-8 col-offset-2">
    <%= form_for(@shoe, html: { multipart: true }) do |f| %>
      <%= f.label "Shoe Brand and Model" %>
      <%= f.text_field :name, :placeholder => "ex. Asics Gel-NIMBUS 17 or Saucony Kinvara 4" %>
      
      <%= f.label "Shoe Information" %>
      <%= f.text_area :description, rows: 10, :placeholder => "Color, Size, Date Purchased, etc." %>
      
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
      
      <%= f.submit(@shoe.new_record? ? 'Save Your Running Shoe' : 'Edit Your Running Shoe', class: "btn btn-success") %>
      
    <% end %>
    
  </div>
  
</div>

<script type="text/javascript">
  $('#shoe_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file');
    }
  });
</script>

app/views/shoes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Your Shoe!" %>

<%= render 'form' %>

app/views/shoes/index.html.erb
<%= render 'shared/page_title', title: "All Shoes" %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Shoes", shoes_path %>
  </li>
  <li>
    <%= link_to "Runners", runners_path %>
  </li>
</ul>

<%= will_paginate %>

  <% @shoes.each do |shoe| %>
    <div class="row">
      
      <div class="col-md-2">
        <section class="runner_info center">
          <%= link_to gravatar_for(shoe.runner, size: 100), runner_path(shoe.runner) %>
          <h5>Runner Name: <%= shoe.runner.runnername %></h5>
        </section>
      </div>
      
      <div class="col-lg-6 well">
        <h4><%= link_to shoe.name, shoe_path(shoe) %></h4>
        <p><%= shoe.summary %></p>
        <p>
          <span class='quiet'>Created <small><%= time_ago_in_words(shoe.created_at) %> ago;
          </small></span>
          <span class='quiet'>Updated <small><%= time_ago_in_words(shoe.updated_at) %> ago
          </small></span>
        </p>
         <div class="pull-right">
          <%= link_to like_shoe_path(shoe, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= shoe.thumbs_up_total %>
          <% end %> &nbsp&nbsp&nbsp&nbsp
          <%= link_to like_shoe_path(shoe, like: false), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= shoe.thumbs_down_total %>
          <% end %>
        </div>
      </div>
      
      <div class="col-md-4">
        <%= image_tag(shoe.picture.url, size: "250x150", class: "gravatar") if shoe.picture? %>
      </div>
      
    </div>
    <hr/>
  <% end %>
  
  <%= will_paginate %>
  

app/views/shoes/new.html.erb
<%= render 'shared/page_title', title: "Create a New Shoe!" %>

<%= render 'form' %>

app/views/shoes/show.html.erb
<%= render 'shared/page_title', title: @shoe.name %>

<div class="row">
  <div class="col-md-4 pull-right center">
    <%= link_to gravatar_for(@shoe.runner, size: 200), runner_path(@shoe.runner) %>
      <p>
        <h5>Brought to you by: <%= @shoe.runner.runnername %></h5>
      </p>
  </div>
  
  <div class="col-md-8">
    <% if logged_in? and @shoe.runner == current_user %>
      <%= link_to "Edit This Shoe", edit_shoe_path(@shoe), class: "btn btn-success pull-right" %>
    <% end %>
    <h3><%= @shoe.summary %></h3>
    <div class="show_shoe">
      <%= image_tag(@shoe.picture.url, class: "gravatar") if @shoe.picture? %>
    </div>
      <div class="well">
        <p>
          <strong>Steps:</strong>
        </p>
        <%= simple_format(@shoe.description) %>
        <div class="pull-right">
          <%= link_to like_shoe_path(@shoe, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @shoe.thumbs_up_total %>
          <% end %> &nbsp&nbsp&nbsp&nbsp
          <%= link_to like_shoe_path(@shoe, like: false), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @shoe.thumbs_down_total %>
          <% end %>
        </div>
      </div>
  </div>
  
</div>

<h5><%= link_to "Return to Shoes Listing", shoes_path, class: "btn btn-warning btn-small" %></h5>